config:
    page.title: 'Widgetized Website'
    backend.title: 'CREA Mini CMS'
    backend.bg: '#f38d00'
    backend.color: '#fff'
    db.host: localhost
    db.user: mkt
    db.pass: 54600
    db.name: htmlwidgetizer
    cache.lifetime: 360