login:
    path: /login
    defaults: { _controller: 'App\Controller\SecurityController::loginAction' }

logout:
    path: /logout
    defaults: { _controller: 'App\Controller\SecurityController::logoutAction' }

index:
    path: /
    defaults: { _controller: 'App\Controller\ContentController::indexAction' }

content_types:
    path: /content/types
    defaults: { _controller: 'App\Controller\ContentController::contentTypesAction' }

content_form:
    path: /content/form/{contentTypeId}/{contentId}
    defaults: { _controller: 'App\Controller\ContentController::formAction', contentId: null }

content_delete:
    path: /content/delete/{contentId}
    defaults: { _controller: 'App\Controller\ContentController::deleteAction' }

content_toggle_active:
    path: /content/toggleactive/{contentId}
    defaults: { _controller: 'App\Controller\ContentController::toggleActiveAction' }

content_category:
    path: /category/{categoryId}
    defaults: { _controller: 'App\Controller\ContentController::indexAction', categoryId: null }

content_category_form:
    path: /content/category/form/{categoryId}
    defaults: { _controller: 'App\Controller\ContentController::categoryFormAction', categoryId: null }

content_category_delete:
    path: /content/category/delete/{categoryId}
    defaults: { _controller: 'App\Controller\ContentController::categoryDeleteAction' }

file_edit:
    path: /file/edit/{file}
    defaults: { _controller: 'App\Controller\FileController::editAction' }
    requirements:
        file: .+

#file_delete:
#    path: /file/delete/{file}
#    defaults: { _controller: 'App\Controller\FileController::deleteAction' }
#    requirements:
#        file: .+

files_clearcache:
    path: /files/clearcache
    defaults: { _controller: 'App\Controller\FileController::clearCacheAction' }

files_tinymce:
    path: /files/tinymce/{dir}
    defaults: { _controller: 'App\Controller\FileController::tinymceAction', dir: '' }
    requirements:
        dir: .+

files:
    path: /files/{dir}
    defaults: { _controller: 'App\Controller\FileController::indexAction', dir: '' }
    requirements:
        dir: .+