services:

    ############
    ### Core ###
    ############

    request:
        class: Symfony\Component\HttpFoundation\Request
        factory: [Symfony\Component\HttpFoundation\Request, createFromGlobals]

    request_context:
        class: Symfony\Component\Routing\RequestContext
        calls: [[fromRequest, ['@request']]]

    session:
        class: Symfony\Component\HttpFoundation\Session\Session

    config:
        class: App\Service\Config

    database:
        class: App\Service\Database
        arguments: ['@config']

    routing:
        class: App\Service\Routing
        arguments: ['@request', '@request_context']

    helper:
        class: App\Service\Helper
        arguments: ['@config', '@database', '@request', '@routing']

    frontend:
        class: App\Service\Frontend


    #####################
    ### Content Types ###
    #####################

    wysiwyg:
        class: App\ContentType\Wysiwyg\Wysiwyg
        tags: [{name: content_type}]

    html:
        class: App\ContentType\Html\Html
        tags: [{name: content_type}]

    facebook_like_box:
        class: App\ContentType\FacebookLikeBox\FacebookLikeBox
        tags: [{name: content_type}]