services:

    ############
    ### Core ###
    ############

    request:
        class: Symfony\Component\HttpFoundation\Request
        factory: [Symfony\Component\HttpFoundation\Request, createFromGlobals]

    request_context:
        class: Symfony\Component\Routing\RequestContext
        calls: [[fromRequest, ['@request']]]

    session:
        class: Symfony\Component\HttpFoundation\Session\Session

    config:
        class: App\Service\Config

    database:
        class: App\Service\Database
        arguments: ['@config']

    routing:
        class: App\Service\Routing
        arguments: ['@request', '@request_context']

    helper:
        class: App\Service\Helper
        arguments: ['@config', '@database', '@request', '@routing']

    translator:
        class: App\Service\Translator
        arguments: ['@config']

    frontend:
        class: App\Service\Frontend

    cache:
        class: App\Service\Cache


    #####################
    ### Content Types ###
    #####################

    wysiwyg:
        class: App\ContentType\Wysiwyg\Wysiwyg
        tags: [{name: content_type}]

    html:
        class: App\ContentType\Html\Html
        tags: [{name: content_type}]

    search:
        class: App\ContentType\Search\Search
        tags: [{name: content_type}]

    facebook_like_box:
        class: App\ContentType\FacebookLikeBox\FacebookLikeBox
        tags: [{name: content_type}]

    facebook_events:
        class: App\ContentType\FacebookEvents\FacebookEvents
        tags: [{name: content_type}]

    facebook_galerie:
        class: App\ContentType\FacebookGalerie\FacebookGalerie
        tags: [{name: content_type}]

    facebook_video:
        class: App\ContentType\FacebookVideo\FacebookVideo
        tags: [{name: content_type}]

    facebook_video_galerie:
        class: App\ContentType\FacebookVideoGalerie\FacebookVideoGalerie
        tags: [{name: content_type}]

    facebook_reviews:
        class: App\ContentType\FacebookFeed\FacebookFeed
        tags: [{name: content_type}]

    instagram_gallery:
        class: App\ContentType\InstagramGallery\InstagramGallery
        tags: [{name: content_type}]

    instagram_photo:
        class: App\ContentType\InstagramPhoto\InstagramPhoto
        tags: [{name: content_type}]

    instagram_button:
        class: App\ContentType\InstagramButton\InstagramButton
        tags: [{name: content_type}]

    twitter_tweet:
        class: App\ContentType\TwitterTweet\TwitterTweet
        tags: [{name: content_type}]

    youtube_video:
        class: App\ContentType\YouTubeVideo\YouTubeVideo
        tags: [{name: content_type}]

    soundcloud_player:
        class: App\ContentType\SoundCloudPlayer\SoundCloudPlayer
        tags: [{name: content_type}]

